[aliases.docker]
c = "rmi $(docker images | grep ... | tr -s ' ' | cut -d' ' -f 3)"
e = "exec -it"
i = "images"
k = "kill"
p = "ps -a"
r = "run -it --rm -v /var/run/docker.sock:/var/run/docker.sock"
s = "stop"
sp = "system prune --volumes --force"

[aliases.kubectl]
a = "apply -f..."
d = "delete -f..."

[aliases.nix]
d = "develop -c $SHELL"
b = "build"

[aliases.pass]
g = "git"
gen = "generate --in-place"
