[aliases.docker]
e = "exec -it"
i = "images"
k = "kill"
s = "stop"
p = "ps -a"
r = "run -it --rm -v /var/run/docker.sock:/var/run/docker.sock"
sp = "system prune --volumes --force"

[aliases.kubectl]
a = "apply -f..."
d = "delete -f..."

[aliases.nix]
d = "develop -c /usr/bin/zsh"
b = "build"

[aliases.pass]
g = "git"
gen = "generate --in-place"
